config/routes.rb
Rails.application.routes.draw do

  #管理者用ログイン
  devise_for :admins, path: 'admin', controllers:{
    sessions: 'admin/sessions'
  }

  #ユーザー用ログイン
  devise_for :users, controllers:{
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  #会員登録画面でバリデーションエラー発生後、リロードするとルーティングエラーが発生していた。その対策用。
  devise_scope :user do 
    unauthenticated do 
      get '/users', to: redirect('/users/sign_up')
    end 
  end 

  #管理者用リソース
  namespace :admin do
    resources :stores, only: [:index, :show, :destroy] do 
      collection do 
        get 'search'
      end 

      resources :comments, only: [:destroy]
    end 

    resources :users, only: [:index, :show] do 
      collection do
        get 'search'
      end 
    end

    resources :comments, only: [:index]
    resources :tags, only: [:index, :create, :destroy]
    resources :categories, only: [:index, :show, :create, :destroy]
    root to: 'homes#top'
  end

 

  #ユーザー用
  scope module: :public do
    #ルート
    root to: 'homes#top'

    get 'about' => 'homes#about'
    get 'mypage', to: 'users#mypage', as: 'mypage'


    #ユーザー編集・更新・退会・検索
    resources :users, only: [:show, :edit, :update, :destroy] do
      collection do 
        get 'search'
      end 
    end 
    
    #投稿機能、コメント、検索
    resources :stores do 
      resources :comments, only: [:create, :destroy]
      collection do 
        get 'search'
      end 
    end 

    resources :categories, only: [:index, :show]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  #アソシエーション
  has_many :stores, dependent: :nullify

  #バリデーション
  validates :name, presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord

  #アソシエーション
  belongs_to :user
  belongs_to :store

  validates :content, presence: true 
end

app/models/store.rb
class Store < ApplicationRecord

#アソシエーション
  belongs_to :user 
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_many_attached :images 
  has_many :store_tags, dependent: :destroy  #中間テーブルとの直接の関連
  has_many :tags, through: :store_tags  #Tagとの間接的な関連
  



#バリデーション
  validates :name, presence: true
  validates :description, presence: true 
  validates :score, presence: true, numericality: { only_integer: true, in: 1..5 }


#地図機能
  geocoded_by :address
  after_validation :geocode 
end

app/models/store_tag.rb
class StoreTag < ApplicationRecord

  #アソシエーション
  belongs_to :store
  belongs_to :tag

  #バリデーション
  validates :store_id, uniqueness: {scope: :tag_id}
end

app/models/tag.rb
class Tag < ApplicationRecord

  #多対多のアソシエーション
  has_many :store_tags  #中間テーブルへの直接の関連
  has_many :stores, through: :store_tags  #Storeとの間接的な関連

  #バリデーション（Tagモデルには別でUNIQUEの制約もかけた）
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
#アソシエーション
  has_many :stores, dependent: :destroy
  has_many :comments, dependent: :destroy


#devise機能
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


#バリデーション
  validates :name, presence: true
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  #管理者かどうかチェック
  before_action :authenticate_admin!

  layout 'admin'
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < Admin::BaseController

  skip_before_action :authenticate_admin!, only: [:top]

  def top
    @stores = Store.order(created_at: :desc).limit(3)
    @categories = Category.all.order(:name)
  end
end

app/controllers/admin/stores_controller.rb
class Admin::StoresController < Admin::BaseController
  def index
    @stores = Store.includes(:user, :tags, :category).order(created_at: :desc).page(params[:page]).per(5)
  end

  def show
    @store = Store.find(params[:id])
    @comments = @store.comments.includes(:user).order(created_at: :asc).page(params[:page]).per(5)
  end

  def search
    @keyword = params[:keyword]
    if @keyword.present?
      @stores = Store.where("name LIKE ? OR description LIKE ?", "%#{@keyword}%", "%#{@keyword}%").page(params[:page]).per(5)
    else
      @stores = Store.none
      flash.now[:alert]="検索結果がありません"
      render :search
    end 
  end

  def destroy
    @store = Store.find(params[:id])
    if @store.destroy
      redirect_to admin_stores_path, notice:"削除できました"
    else
      render :show, alert: "削除に失敗しました"
    end 
  end 
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < Admin::BaseController
  def index 
    @tags = Tag.all
    @tag = Tag.new
  end 

  def create 
    @tag = Tag.new(tag_params)
    if @tag.save 
      redirect_to admin_tags_path, notice: 'タグを作成しました'
    else 
      @tags = Tag.all   #エラー時に一覧を再表示するために必要
      render :index 
    end 
  end 

  def destroy
    tag = Tag.find(params[:id])
    tag.destroy
    redirect_to admin_tags_path, notice: 'タグを削除しました'
  end 

  
  private

  def tag_params
    params.require(:tag).permit(:name)
  end 
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  def index
    @users = User.all.includes(:stores, :comments)
  end

  def show
    @user = User.find(params[:id])
    @stores = @user.stores.order(created_at: :desc).page(params[:stores_page]).per(3)
    @comments = @user.comments.order(created_at: :desc).includes(:store).page(params[:comments_page]).per(5)
  end 

  def search
    @keyword = params[:keyword]
    if @keyword.present?
      @users = User.where("name LIKE ?", "%#{@keyword}%")
    else
      @users = User.none
      flash.now[:alert] = "該当するユーザーはいません"
      render :search
    end 
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_pemitted_parameters, if: :devise_controller?


  protected

  def configure_pemitted_parameters

    #新規登録時にnameを許可
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    #アカウント編集時にnameを許可
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end 

  def after_sign_in_path_for(resource)
    if resource.is_a?(Admin)
      admin_root_path
    elsif resource.is_a?(User)
      mypage_path
    else 
      root_path 
    end 
  end 
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/stores_helper.rb
module Admin::StoresHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/admin/tops_helper.rb
module Admin::TopsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/stores/index.html.erb
<h3>店舗一覧ページ</h3>

<!--店舗検索のフォーム-->
<div class="mb-4">
  <%= form_with url:search_admin_stores_path, method: :get, local: true do |f| %>
    <%= f.text_field :keyword, placeholder: "店舗名や特徴" %>
    <%= f.submit "検索する" %>
  <% end %>
</div
>
<!--店舗一覧-->
<%= render 'admin/shared/store_list', stores: @stores %>


<!--ページネーションの表示-->
<div class="d-flex justify-content-center">
  <%= paginate @stores %>
</div>

app/views/admin/stores/search.html.erb
<h3 class="mb-4">店舗検索結果</h3>

<!--店舗検索結果一覧-->
<%= render 'admin/shared/store_list', stores: @stores %>


<!--ページネーションの表示-->
<div class="d-flex justify-content-center">
  <%= paginate @stores %>
</div>

app/views/admin/stores/show.html.erb
<h4 class="mb-4">店舗詳細ページ</h4>

<% if @store.images.attached? %>
  <div class="row">
    <div class="col-md-12">
      <% @store.images.each do |image| %>
        <%= image_tag image.variant(resize_to_limit: [600, 400]), class: "img-fluid rounded" %>
      <% end %>
    </div>
  </div>
<% end %>

<div class="row mt-4">
  <div class="col-md-12">
    <h4>店舗名：<%= @store.name %></h4>
    <p>カテゴリ：<%= @store.category.name %></p>

    <% @store.tags.each do |tag| %>
      <p>タグ：<%= tag.name %></p>
    <% end %>

    <p>評価：<%= @store.score %></p>
    <p>レビュー：<%= @store.description %></p>
    <p>郵便番号：<%= @store.zip_code %></p>
    <p>住所：<%= @store.address %></p>
    <p>感情分析値：<%= @store.sentiment_score %></p>
    <p>投稿者：<%= link_to @store.user.name, user_path(@store.user) %></p>

    <% if admin_signed_in? %>
      <%= link_to '投稿を削除する', admin_store_path(@store), method: :delete, class: "btn btn-outline-danger btn-sm", data:{confirm: '本当に削除しますか？'} %>
    <% end %>

    <hr>

    <h4 class="mt-4">コメント一覧</h4>
    <% @comments.each do |comment| %>
      <div class="border p-2 mb-2">

        <p><%= comment.content %></p>
        <p>コメント者：<%= link_to comment.user.name, admin_user_path(comment.user) %></p>

        <% if admin_signed_in? %>
          <%= link_to 'コメントを削除する', admin_store_comment_path(@store,comment), method: :delete, class: "btn btn-outline-danger btn-sm", data:{confirm: '本当に削除しますか？'} %>
        <% end %>

      </div>
    <% end %>

    <!--ページネーションの表示-->
    <div class="d-flex justify-content-center">
      <%= paginate @comments %>
    </div>
  </div>
</div>

app/views/admin/tags/index.html.erb
<h4 class="mb-4">タグの管理ページ</h4>

<ul class="list-group mb-4">
  <% @tags.each do |tag| %>
    <li class="list-group-item d-flex align-items-center" >
      <span class="me-3" style="width: 7rem;" ><%= tag.name %></span>
      <%= link_to '削除', admin_tag_path(tag), method:  :delete, data: {confirm: "本当に削除しますか？"}, class:"btn btn-sm btn-danger" %>
    </li>
  <% end %>
</ul>

<%= form_with model: [:admin, @tag], local: true do |f| %>

  <!--エラーメッセージ呼び出し用-->
  <%= render 'admin/shared/error_messages', resource: @tag %>  

  <div class="form-group">
    <h5>新しくタグを追加する</h5>
    <%= f.text_field :name, class: "form-control", placeholder: "追加するタグ名" %>
  </div>

  <%= f.submit "タグを追加", class: "btn btn-primary mt-2" %>
<% end %>

app/views/admin/users/index.html.erb
<h3 class="mb-4">会員一覧ページ</h3>

<!--ユーザーを検索するフォーム-->
<div class="mb-4">
  <%= form_with url: search_admin_users_path, method: :get, local: true do |f| %>
    <%= f.label :keyword, "ユーザー検索" %>
    <%= f.text_field :keyword, placeholder: "ユーザー名" %>
    <%= f.submit "検索", class: "btn btn-primary" %>
  <% end %>
</div>

<!--会員一覧の表-->
<%= render 'admin/shared/user_list', users: @users %>

app/views/admin/users/search.html.erb
<h3>adminユーザー検索結果ページ</h3>

<!--会員一覧の表-->
<%= render 'admin/shared/user_list', users: @users %>

app/views/admin/users/show.html.erb
<!--ユーザーの詳細ページ-->

<h3><%= @user.name %>さんの詳細ページ</h3>

<h3>投稿一覧(<%= @stores.total_count %>件)</h3>
<% if @stores.present? %>
  <div class="row">
    <% @stores.each do |store| %>
      <div class="col-md-4 mb-3">
        <%= link_to admin_store_path(store), class: "text-reset text-decoration-none" do %>
          <div class= "card h-100">

            <% if store.images.attached? %>
              <%= image_tag store.images.first, class: "card-img-top", style: "height: 200px; object-fit: contain;" %>
            <% else %>
              <p>画像はありません</p>
            <% end %>

            <div class="card-body">
              <h5 class="card-title"><%= store.name %></h5>
              <p><%= l(store.created_at, format: :short) %></p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <%= paginate @stores, param_name: :stores_page %>
<% else %>
  <p>投稿はありません</p>
<% end %>


<h3>コメント一覧（<%= @comments.total_count %>件）</h3>
<% if @comments.present? %>
  <% @comments.each do |comment| %>
    <div><%= link_to comment.store.name, store_path(comment.store) %>へのコメント：<%= truncate(comment.content, length: 30) %></div>
  <% end %>
  <%= paginate @comments, param_name: :comments_page %>
<% else %>
  <p>まだコメントがありません</p>
<% end %>