config/routes.rb
Rails.application.routes.draw do

  #管理者用ログイン
  devise_for :admins, path: 'admin', controllers:{
    sessions: 'admin/sessions'
  }

  #ユーザー用ログイン
  devise_for :users, controllers:{
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  #会員登録画面でバリデーションエラー発生後、リロードするとルーティングエラーが発生していた。その対策用。
  devise_scope :user do 
    unauthenticated do 
      get '/users', to: redirect('/users/sign_up')
    end 
  end 

  #管理者用リソース
  namespace :admin do
    resources :stores, only: [:index, :show, :destroy] do 
      collection do 
        get 'search'
      end 

      resources :comments, only: [:destroy]
    end 

    resources :users, only: [:index, :show] do 
      collection do
        get 'search'
      end 
    end

    resources :comments, only: [:index]
    resources :tags, only: [:index, :create, :destroy]
    resources :categories, only: [:index, :show, :create, :destroy]
    root to: 'homes#top'
  end

 

  #ユーザー用
  scope module: :public do
    #ルート
    root to: 'homes#top'

    get 'about' => 'homes#about'
    get 'mypage', to: 'users#mypage', as: 'mypage'


    #ユーザー編集・更新・退会・検索
    resources :users, only: [:show, :edit, :update, :destroy] do
      collection do 
        get 'search'
      end 
    end 
    
    #投稿機能、コメント、検索
    resources :stores do 
      resources :comments, only: [:create, :destroy]
      collection do 
        get 'search'
      end 
    end 

    resources :categories, only: [:index, :show]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  #アソシエーション
  has_many :stores, dependent: :nullify

  #バリデーション
  validates :name, presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord

  #アソシエーション
  belongs_to :user
  belongs_to :store

  validates :content, presence: true 
end

app/models/store.rb
class Store < ApplicationRecord

#アソシエーション
  belongs_to :user 
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_many_attached :images 
  has_many :store_tags, dependent: :destroy  #中間テーブルとの直接の関連
  has_many :tags, through: :store_tags  #Tagとの間接的な関連
  



#バリデーション
  validates :name, presence: true
  validates :description, presence: true 
  validates :score, presence: true, numericality: { only_integer: true, in: 1..5 }


#地図機能
  geocoded_by :address
  after_validation :geocode 
end

app/models/store_tag.rb
class StoreTag < ApplicationRecord

  #アソシエーション
  belongs_to :store
  belongs_to :tag

  #バリデーション
  validates :store_id, uniqueness: {scope: :tag_id}
end

app/models/tag.rb
class Tag < ApplicationRecord

  #多対多のアソシエーション
  has_many :store_tags  #中間テーブルへの直接の関連
  has_many :stores, through: :store_tags  #Storeとの間接的な関連

  #バリデーション（Tagモデルには別でUNIQUEの制約もかけた）
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
#アソシエーション
  has_many :stores, dependent: :destroy
  has_many :comments, dependent: :destroy


#devise機能
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


#バリデーション
  validates :name, presence: true
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  #管理者かどうかチェック
  before_action :authenticate_admin!

  layout 'admin'
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < Admin::BaseController

  skip_before_action :authenticate_admin!, only: [:top]

  def top
    @stores = Store.order(created_at: :desc).limit(3)
    @categories = Category.all.order(:name)
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < Admin::BaseController
  def index 
    @tags = Tag.all
    @tag = Tag.new
  end 

  def create 
    @tag = Tag.new(tag_params)
    if @tag.save 
      redirect_to admin_tags_path, notice: 'タグを作成しました'
    else 
      @tags = Tag.all   #エラー時に一覧を再表示するために必要
      render :index 
    end 
  end 

  def destroy
    tag = Tag.find(params[:id])
    tag.destroy
    redirect_to admin_tags_path, notice: 'タグを削除しました'
  end 

  
  private

  def tag_params
    params.require(:tag).permit(:name)
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_pemitted_parameters, if: :devise_controller?


  protected

  def configure_pemitted_parameters

    #新規登録時にnameを許可
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    #アカウント編集時にnameを許可
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end 

  def after_sign_in_path_for(resource)
    if resource.is_a?(Admin)
      admin_root_path
    elsif resource.is_a?(User)
      mypage_path
    else 
      root_path 
    end 
  end 
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/stores_helper.rb
module Admin::StoresHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/admin/tops_helper.rb
module Admin::TopsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_category_sidebar.html.erb
<!--サイドバー-->
<ul class="list-group">
  <% categories.each do |cat| %>
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <%= link_to cat.name, admin_category_path(cat) %>
      <span class="badge badge-secondary badge-pill">
        <%= cat.stores.count %>
      </span>
  <% end %>
</ul>

app/views/admin/shared/_error_messages.html.erb
<!--エラーメッセージのパーシャル-->

<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "会員登録", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードをお忘れですか？", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/admin/shared/_shop_card_list.html.erb
<!--ダッシュボードの店舗一覧で使用-->

<div class="row">
  <% stores.each do |store| %>
    <div class="col-md-4 mb-3">
      <div class="card h-100">

        <% if store.images.attached? %>
          <%= image_tag store.images.first, class: "card-img-top", style: "height: 200px; object-fit: contain;" %>
        <% else %>
          <p>画像はありません</p>
        <% end %>

        <div class="card-body d-flex flex-column align-items-center">
          <h5 class="card-title text-center"><%= store.name %></h5>
          <%= link_to '詳細を見る', admin_store_path(store), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/shared/_store_list.html.erb
<!--店舗一覧・店舗検索結果ページで使うパーシャル-->


<div class="row">
  <% if stores.any? %>
    <% stores.each do |store| %>
      <div class="col-md-5 mb-4">
        <% if store.images.attached? %>
          <%= link_to admin_store_path(store) do %>
            <%= image_tag store.images.first.variant(resize_to_limit: [600,400]), class:"img-fluid" %>
          <% end %>
        <% else %>
          <p>画像がありません</p>
        <% end %>
      </div>

      <div class="col-md-7">
        <p>店舗名：<strong><%= store.name%></strong></p>
        <p>投稿者：<%= store.user.name %></p>
        <p>評価：<%= store.score %></p>
        <p>カテゴリ：<%= store.category.name %></p>
        <p>
          <% store.tags.each do |tag| %>
            <span>タグ：<%= tag.name %></span>
          <% end %>
        </p>
        <p>レビュー：<%= truncate(store.description, length: 100) %></p>
        <p><%= link_to "この店舗の詳細をみる", admin_store_path(store) %></p>

      </div>
    <% end %>
  <% else %>
    <p>まだ投稿がありません</p>
  <% end %> 
</div>

app/views/admin/shared/_user_list.html.erb
<!--会員一覧、会員検索結果一覧ページで使う-->
<table class="table">

  <thead>
    <tr>
      <th>ユーザー名</th>
      <th>投稿数</th>
      <th>コメント数</th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= link_to user.name, admin_user_path(user) %></td>
        <td><%= user.stores.count %></td>
        <td><%= user.comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_admin_header.html.erb
<!--管理者側のヘッダー-->
<nav class="navbar navbar-expand-lg navbar-light bg-light" >
  <%= link_to admin_root_path class: "navbar-brand" do %>
    <%= image_tag 'logo.png', alt: 'with baby logo', class:'header-logo' %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
    <ul class="navbar-nav">
      <% if admin_signed_in? %>
        <li class="nav-item"><%= link_to 'ユーザー', admin_users_path, class: "nav-link text-center" %></li>
        <li class="nav-item"><%= link_to '店舗', admin_stores_path, class: "nav-link text-center" %></li>
        <li class="nav-item"><%= link_to 'コメント', admin_comments_path, class: "nav-link text-center" %></li>
        <li class="nav-item"><%= link_to 'カテゴリ', admin_categories_path, class: "nav-link text-center" %></li>
        <li class="nav-item"><%= link_to 'タグ', admin_tags_path, class:"nav-link text-center" %></li>
        <li class="nav-item"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link text-center" %></li>
      <% else %>
        <li class="nav-item"><%= link_to '管理者ログイン', new_admin_session_path, class: "nav-link text-center" %></li>
        <li class="nav-item"><%= link_to '会員トップページへ', root_path, class: "nav-link text-center" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_header.html.erb
<!--  会員側のヘッダー -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to root_path, class:"navbar-brand" do %>
    <%= image_tag 'logo.png', alt:'with baby logo', class:'header-logo' %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item"><%= link_to "店舗一覧", stores_path, class: "nav-link text-center" %></li>
        <li class="nav-item"><%= link_to "新規店舗登録", new_store_path, class: "nav-link text-center", data: {turbolinks: "false"}  %></li>
        <li class="nav-item"><%= link_to "マイページ", mypage_path, class: "nav-link text-center" %></li>
        <li class="nav-item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link text-center" %></li>
      <% else %>
        <li class="nav-item"><%= link_to "ログイン", new_user_session_path, class: "nav-link text-center" %></li>
        <li class="nav-item"><%= link_to "会員登録", new_user_registration_path, class: "nav-link text-center" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!--admin側のレイアウトファイル-->
<!DOCTYPE html>
<html>
  <head>
    <title>管理者画面</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="container">
        <%= render 'layouts/admin_header' %>
      </div>
    </header>

    <hr>

    <main class="container">
      <%= render 'shared/flash_messages' %>
      <%= yield %>
    </main>

    <hr class="my-4">

    <footer class="text-center py-3">
      <p>© 2025 With Baby All Rights Reserved.</p>
    </footer>

  <!--住所の自動入力に必要-->
  <script src="https://cdn.jsdelivr.net/npm/jquery-jpostal-ja@2.14.45/jquery.jpostal.min.js"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<!--public側のレイアウトファイル-->
<!DOCTYPE html>
<html>
  <head>
    <title>WithBaby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="container">
      <%= render 'layouts/header' %>
    </header>

    <hr>

    <main class="container">
      <%= render 'shared/flash_messages' %>
      <%= yield %>
    </main>

    <hr class="my-4">

    <footer class="text-center py-3">
      <p>© 2025 With Baby All Rights Reserved.</p>
    </footer>
  
  <!--住所の自動入力に必要-->
  <script src="https://cdn.jsdelivr.net/npm/jquery-jpostal-ja@2.14.45/jquery.jpostal.min.js"></script>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<!--adminとpublic共通のフラッシュメッセージのパーシャル-->
<% flash.each do |key, message| %>
  
  <% alert_class = case key.to_sym
    when :notice then 'alert-success'
    when :alert then 'alert-danger'
    when :warning then 'alert-warning'
    else 'alert-info'
    end %>

  
  <div class="alert <%= alert_class %> alert-dismissible fade show mt-3" role="alert">
    <%= message %>
    <button type="button" class="close" data-dismiss="alert">
      <span>&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_store_list.html.erb
<div class="row">
  <% if stores.any? %>
    <% stores.each do |store| %>
      <div class="col-md-5">
        <% if store.images.attached? %>
          <%= link_to store_path(store) do %>
            <%= image_tag store.images.first.variant(resize_to_limit: [600,400]), class:"img-fluid" %>
          <% end %>
        <% else %>
          <p>画像がありません</p>
        <% end %>
      </div>

      <div class="col-md-7">
        <p>店舗名：<strong><%= store.name%></strong></p>
        <p>投稿者：<%= store.user.name %></p>
        <p>評価：<%= store.score %></p>
        <p>カテゴリ：<%= store.category.name %></p>
        <p>
          <% store.tags.each do |tag| %>
            <span>タグ：<%= tag.name %></span>
          <% end %>
        </p>
        <p>レビュー：<%= truncate(store.description, length: 100) %></p>
        <p><%= link_to "この店舗の詳細をみる", store_path(store) %></p>

      </div>
    <% end %>
  <% else %>
    <p>まだ投稿がありません</p>
  <% end %> 
</div>